# Generated by Django 3.2.8 on 2021-10-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imgUrl',
            field=models.TextField(default='', max_length=250),
        ),
    ]
